// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Space.Models
{
    public partial class Constellations
    {
        public Constellations()
        {
            BlackHoles = new HashSet<BlackHoles>();
            Galaxies = new HashSet<Galaxies>();
            GalaxyClusters = new HashSet<GalaxyClusters>();
            GalaxyGroups = new HashSet<GalaxyGroups>();
            Nebulae = new HashSet<Nebulae>();
            PlanetarySystems = new HashSet<PlanetarySystems>();
            Planets = new HashSet<Planets>();
            StarClusters = new HashSet<StarClusters>();
            Stars = new HashSet<Stars>();
        }

        public int ConsId { get; set; }
        public string ConsName { get; set; }
        public string ConsAbbreviation { get; set; }
        public string ConsSymbolism { get; set; }
        public string ConsRightAscension { get; set; }
        public string ConsDeclination { get; set; }
        public int? ConsSquare { get; set; }
        public string ConsVisibleInLatitudes { get; set; }

        public virtual ICollection<BlackHoles> BlackHoles { get; set; }
        public virtual ICollection<Galaxies> Galaxies { get; set; }
        public virtual ICollection<GalaxyClusters> GalaxyClusters { get; set; }
        public virtual ICollection<GalaxyGroups> GalaxyGroups { get; set; }
        public virtual ICollection<Nebulae> Nebulae { get; set; }
        public virtual ICollection<PlanetarySystems> PlanetarySystems { get; set; }
        public virtual ICollection<Planets> Planets { get; set; }
        public virtual ICollection<StarClusters> StarClusters { get; set; }
        public virtual ICollection<Stars> Stars { get; set; }
    }
}