// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Space.Models
{
    public partial class GalaxyClusters
    {
        public GalaxyClusters()
        {
            Galaxies = new HashSet<Galaxies>();
        }

        public int GlxclusterId { get; set; }
        public int ConsId { get; set; }
        public string GlxclusterName { get; set; }
        public string GlxclusterType { get; set; }
        public TimeSpan? GlxclusterRightAscension { get; set; }
        public string GlxclusterDeclination { get; set; }
        public double? GlxclusterRedshift { get; set; }

        public virtual Constellations Cons { get; set; }
        public virtual ICollection<Galaxies> Galaxies { get; set; }
    }
}