// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Space.Models
{
    public partial class Stars
    {
        public Stars()
        {
            Asteroids = new HashSet<Asteroids>();
            Comets = new HashSet<Comets>();
            Planets = new HashSet<Planets>();
        }

        public int StarId { get; set; }
        public int? ConsId { get; set; }
        public int? GlxId { get; set; }
        public int? StarclusterId { get; set; }
        public int? PlanetsystemId { get; set; }
        public string StarName { get; set; }
        public double? StarApparentMagnitude { get; set; }
        public string StarStellarClass { get; set; }
        public double? StarDistance { get; set; }
        public string StarDeclination { get; set; }

        public virtual Constellations Cons { get; set; }
        public virtual Galaxies Glx { get; set; }
        public virtual PlanetarySystems Planetsystem { get; set; }
        public virtual StarClusters Starcluster { get; set; }
        public virtual ICollection<Asteroids> Asteroids { get; set; }
        public virtual ICollection<Comets> Comets { get; set; }
        public virtual ICollection<Planets> Planets { get; set; }
    }
}